### PR TITLE
Allow users to specify a decryption key for messages

### PR DESCRIPTION
**Pull request by jfenske89**
**Feature**:
 - Added a checkbox that is disabled by default, which will allow the user to enter a decryption key manually when checked.
 - Base64 encoding the password in URLs so that special characters are supported.
 - Updated tests for the Base64 change (**note**: these tests were previously failing, and have not been fixed by these changes - `App.text.tsx` and `Upload.test.tsx`)

**Preview**:

https://1drv.ms/u/s!AjyD1azsNt_ehLVMMUnWtjEBRUCK7g?e=X2IMxf

**Additional changes**:
 - Fixed: the text was not displayed in English - "Yopass generates a unique one click link for the encrypted file or message. The decryption password can alternatively be sent separately."

### CODE REVIEW

**Comment by jhaals** [comment]
Thanks for the contribution!
I'm not opposed to having a way of manually setting the password however I'm not a big fan of the current layout. Perhaps it can be hidden or toggled somehow.

Sorry for the late reply I've been on vacation until this week, I will try to fix the tests that broke due to a dependency bump by dependabot.

**Comment by jfenske89** [comment]
@jhaals thanks for the suggestion. I will experiment more with the design and get back to you.

**Comment by jfenske89** [comment]
@jhaals I have updated the field to be hidden by default. Please review as time permits, and let me know if you have any suggestions:

https://1drv.ms/u/s!AjyD1azsNt_ehLVk8nlwnbvMhFVGrA?e=kCff1q

In addition to that, I added some basic unit tests for the password field. There is an issue with testing-library regarding the waitFor* methods: https://github.com/testing-library/react-testing-library/issues/662, so to get around that I am using jsdom-sixteen in the new test only.

**Comment by jhaals** [comment]
Hi @jfenske89, thanks for doing another iteration on this!
This looks a lot better and I will happily accept this feature.

I also noticed that the tests are broken, not your fault but I'm so fed up with the wonky and often failing react-testing so I switched to cypress for some more high level end to end test.
The build is passing now because it's doing the cypress test instead of the react-tests. I'm going to delete the old tests very soon.
It would be fantastic if you could add an integration test similar to the create_secret one in this folder, I believe you can copy most of it; https://github.com/jhaals/yopass/tree/master/website/cypress/integration

It's easy to test locally if you `yarn start` the web server and run `yarn cypress open -b chrome` in another tab (both from inside the website directory.

**Comment by jfenske89** [comment]
@jhaals I moved the test as suggested. Using cypress was a big improvement. Thanks for pointing me in the right direction.

**Comment by jhaals** [comment]
Thanks for the contribution @jfenske89!

**Comment by grobie** [comment]
If I understand correctly, this change will break any already existing secret due to the new requirement of base64 encoding passwords. It might be a good idea to handle non-base64 encoded passwords gracefully for some time. Maybe we can at least warn users in the changelog about this change?

**Comment by jhaals** [comment]
@grobie That's correct, thanks for suggesting the optional base64, that would be a smoother transition. I have not put out a release for this but I was aiming for a breaking 9.0 release but it might not be needed with your suggestion

**Comment by jhaals** [comment]
@grobie @jfenske89 I have started to get second thoughts about releasing this due to the base64 encoding.
Primarily due to the one click urls being different from the passwords, and the longer URLs. 

base64 vs normal.
Nmd2c0VQS09IeEhDRk9EVWFTcWhtVg==
6gvsEPKOHxHCFODUaSqhmV

I'm not sure there is a good way to do this when needed.

**Comment by jhaals** [comment]
Perhaps the easiest way is have a separate url for those secrets created with a custom passwords not to confuse people that might otherwise be used to just placing the password at the end of the URL. 
instead of /s/ there could be /c/ urls, that way we would know if the password would need to be base64 encoded.

**Comment by grobie** [comment]
Having a separate path would help to separate the two cases for sure. Though I'm not sure I fully understand the need for the feature of specifying passwords manually. My only assumption was that the need is to deliver the password out-of-band and have agreed upon the password in advance. In that case, it wouldn't be desired to have the password in the URL at all, right?

**Comment by jhaals** [comment]
That's a very good point. Having a one click url would be very strange if you agree on a password.
Then I vote for a separate path and that providing the password on the url is no longer and option if a custom password is used. I lifted the current custom password functionality out from the master branch in order for not to block further releases until this change is implemented.

**Comment by jfenske89** [comment]
Okay, this sounds good to me. I will try to work on that if I have some free time this weekend

**Pull request merged**
