### PR TITLE
Implement Redis database as alternative storage

### PR DESCRIPTION
**Pull request by hlubek**
This change adds a new `Database` implementation for storing encrypted secrets in Redis - which provides a key/value store with persistence of values between restarts.

Either implementation can be chosen by specifying the according command line flag.

### CODE REVIEW

**Comment by jhaals** [comment]
Thanks for the pull request @hlubek!

**Comment by jhaals** [comment]
I took at look at the code and it looks good overall 👍 
However I think the initial command line parsing could be slightly improved:
So instead of relying on either --redis or --memcached being set add a separate --database flag and convert the if statements in main to a switch which loads the correct database. Both memcached and redis can be kept with a sane default instead of empty strings.

**Comment by hlubek** [comment]
Thx for the suggestion, makes sense. I updated the code accordingly.

**Comment by jhaals** [comment]
@hlubek thanks for the update! Final nitpick regarding the Readme. 
Please update it so that it mention --database instead of --redis and --memcached

**Pull request merged**
