### PR TITLE
Switch key generation to Crypto.getRandomValues

### LINKED ISSUE #173: Non-crypto-safe key generation
It seems like keys are generated using [Math.random()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random):
https://github.com/jhaals/yopass/blob/ec6279316caec9809d75eb4884616935acd50b81/website/src/Create.tsx#L33
https://github.com/jhaals/yopass/blob/ec6279316caec9809d75eb4884616935acd50b81/website/src/Create.tsx#L149
That method cannot be used to generate cryptographically secure random data.
A method like [Crypto​.get​Random​Values()](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) should be used instead.

### PR DESCRIPTION
**Pull request by jhaals**
Pick numbers within range from generated array using rejection sampling.

Fixed #173

### CODE REVIEW

**Comment by jhaals** [comment]
@marcobellaccini this should address your issue. Feel free to take a look

**Comment by marcobellaccini** [comment]
Hi!
I'm afraid that this `range` definition may lead to problems:
https://github.com/jhaals/yopass/blob/f6f0ab778f657d3e49b1d8afa26a18a151fc6f6c/website/src/Create.tsx#L158

In fact, looking at this if statement:
https://github.com/jhaals/yopass/blob/f6f0ab778f657d3e49b1d8afa26a18a151fc6f6c/website/src/Create.tsx#L160

the maximum `byteArray[0]` value that won't end up in recursion is:

`byteArray[0] = (Math.floor(maxRange / range) * range) - 1;`

However, with this value, `possible.charAt()` will go out of range.

So, I think that you should set:

`const range = max - min;`

Apart from this, I see that you're using a 16-symbols password from this alphabet:

https://github.com/jhaals/yopass/blob/f6f0ab778f657d3e49b1d8afa26a18a151fc6f6c/website/src/Create.tsx#L147

so, there are 62 possible symbols: about 6 bits of entropy/symbol.

With a 16-symbols password you have a 6*16 = 96 bits key.

Not so bad, but... how about a 22-symbols password (so that you're over 128 bits)?

Cheers

Marco

**Comment by jhaals** [comment]
Good catch @marcobellaccini and thanks for the suggestion about improving the password length. I've addressed those in #188. Feel free to take a look.

Btw I have been thinking about maybe switching from sjcl to aes-gcm or similar now that the built-in Crypto are in major browsers. This would allow for easier integrations with other languages and CLI tools. Do you have any suggestions?

Best,
Johan

**Comment by marcobellaccini** [comment]
You are welcome!

Of course, using browser's built-in crypto has many advantages in terms of performance, implementation security and integration with other tools.

Nevertheless, you should be careful with the Web Crypto API: as you can read [here](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API), it provides low-level crypto primitives.
This means that it is extremely easy to misuse, hence harming security.

As [Uncle Ben](https://en.wikipedia.org/wiki/With_great_power_comes_great_responsibility) would say: _With great power comes great responsibility_.

When using low-level crypto primitives, you have to take care of everything regarding crypto:
- What encryption algorithm should I choose?
- In what encryption mode?
- How do I derive the key from the password?
- What parameters should I set for the key derivation function?
- Does the selected encryption scheme need a nonce? If so, how do I generate it?
- Etc. etc.

Doing "good" crypto is a job on its own.

Despite some drawbacks, SJCL provides you with a high-level, easy-to-use API.

Therefore, instead of switching to Web Crypto API, I would rather stick with SJCL until you find some **mainstream** JS library exposing high-level crypto API that, in turn, is based on the built-in, low-level Web Crypto API.

Is there already such a library?

Sincerely I do not know (and I am not the right person to help you with this, since I suck as front-end developer)...

**Comment by jhaals** [comment]
I agree with your points and that's the main reason why I kept with SJCL but many of the features like secure key/nonce generation are now in built-in so it might be possible to revisit, with caution of course. Thanks again!

/Johan

**Pull request merged**
