### PR TITLE
Watch for error when generating UUID

### PR DESCRIPTION
**Pull request by zostay**

### CODE REVIEW

**Comment by jhaals** [comment]
Thanks for the PR @zostay!
Just want to understand the reasoning behind the version upgrade of the uuid library, doesn't version v1.2.0 have return an error?

If it does not return error in 1.2.0 and the upgrade is needed, please run `go mod tidy` and commit the go.sum since that's still pointing to the old version.

**Comment by zostay** [comment]
Sorry for not being complete. I was being lazy and doing most of the editing through github. The version upgrade is required because prior to the latest, `NewV4()` returns only the UUID. 

I'll look into cleaning up when I have time later today.

**Comment by zostay** [comment]
Sorry for the multiple forces, but I cleaned up the mess that was the previous change branch.

**Comment by jhaals** [comment]
Hey @zostay looks like you almost got it, please remove the older gorilla mux from go.mod

**Comment by jhaals** [comment]
Closing due to inactivity, feel free to re-open once it's rebased 👍

**Pull request closed without merging**
