### PR TITLE
Update existing Docker Compose file, add new one to get full set up with TLS and cert auto renewal

### PR DESCRIPTION
**Pull request by flobeier**
I created this PR because an acquaintance was notified by the German CERT Bund that he was running an open memcached instance. I think it is important to provide safe default options because users will copy commands without fully understanding them in order to get a program running.
Therefore I updated the existing Docker Compose file so it doesn't expose memcached and yopass on every interface anymore and added a new Docker Compose file that can be used to get yopass running with TLS encryption and certificate auto renewal. I think this will help users to host yopass themselves more easily since they just need to point a DNS entry to their host.

Please test before merging.

### CODE REVIEW

**Comment by jhaals** [comment]
Thanks for the PR @flobeier, I'm all for sane defaults.
The let's encrypt setup did not manage to run on my machine.

it exited with 
```
nginx-proxy-letsencrypt_1  | Error: can't get nginx-proxy container ID !
nginx-proxy-letsencrypt_1  | Check that you are doing one of the following :
nginx-proxy-letsencrypt_1  | 	- Use the --volumes-from option to mount volumes from the nginx-proxy container.
nginx-proxy-letsencrypt_1  | 	- Set the NGINX_PROXY_CONTAINER env var on the letsencrypt-companion container to the name of the nginx-proxy container.
nginx-proxy-letsencrypt_1  | 	- Label the nginx-proxy container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'.
```

**Comment by flobeier** [comment]
@jhaals I added the missing label, please try again.

**Comment by jhaals** [comment]
Hi @flobeier 

It still seems like it does not work quite right

```
Creating with-nginx-proxy-and-letsencrypt_memcached_1               ... done
Creating with-nginx-proxy-and-letsencrypt_yopass_1                  ... done
Creating with-nginx-proxy-and-letsencrypt_nginx-proxy_1             ... done
Creating with-nginx-proxy-and-letsencrypt_nginx-proxy-letsencrypt_1 ... done
Attaching to with-nginx-proxy-and-letsencrypt_memcached_1, with-nginx-proxy-and-letsencrypt_yopass_1, with-nginx-proxy-and-letsencrypt_nginx-proxy-letsencrypt_1, with-nginx-proxy-and-letsencrypt_nginx-proxy_1
nginx-proxy_1              | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
nginx-proxy_1              | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
nginx-proxy-letsencrypt_1  | Info: running letsencrypt-nginx-proxy-companion version v2.0.0-65-g53d2ac1
yopass_1                   | 2021/04/07 11:25:20 Starting yopass server on :80, configured Memcached address: memcached:11211
nginx-proxy_1              | forego     | starting dockergen.1 on port 5000
nginx-proxy_1              | forego     | starting nginx.1 on port 5100
nginx-proxy-letsencrypt_1  | Error: can't get nginx-proxy container ID !
nginx-proxy-letsencrypt_1  | Check that you are doing one of the following :
nginx-proxy-letsencrypt_1  | 	- Use the --volumes-from option to mount volumes from the nginx-proxy container.
nginx-proxy-letsencrypt_1  | 	- Set the NGINX_PROXY_CONTAINER env var on the letsencrypt-companion container to the name of the nginx-proxy container.
nginx-proxy-letsencrypt_1  | 	- Label the nginx-proxy container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'.
nginx-proxy-letsencrypt_1  | Error: can't write to the '/etc/nginx/certs' directory !
nginx-proxy-letsencrypt_1  | Check that '/etc/nginx/certs' directory is export as a writable volume.
with-nginx-proxy-and-letsencrypt_nginx-proxy-letsencrypt_1 exited with code 1
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:22 Generated '/etc/nginx/conf.d/default.conf' from 4 containers
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:22 Running 'nginx -s reload'
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:22 Watching docker events
nginx-proxy-letsencrypt_1  | Error: can't write to the '/etc/nginx/certs' directory !
nginx-proxy-letsencrypt_1  | Check that '/etc/nginx/certs' directory is export as a writable volume.
with-nginx-proxy-and-letsencrypt_nginx-proxy-letsencrypt_1 exited with code 1
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:24 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:24 Received event die for container e371e147a6bd
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:24 Received event start for container e371e147a6bd
nginx-proxy-letsencrypt_1  | Error: can't write to the '/etc/nginx/certs' directory !
nginx-proxy-letsencrypt_1  | Check that '/etc/nginx/certs' directory is export as a writable volume.
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:25 Received event die for container e371e147a6bd
with-nginx-proxy-and-letsencrypt_nginx-proxy-letsencrypt_1 exited with code 1
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:25 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy_1              | 2021/04/07 11:25:25 [notice] 48#48: signal process started
nginx-proxy_1              | Generating DSA parameters, 4096 bit long prime
nginx-proxy_1              | dhparam generation complete, reloading nginx
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:26 Received event start for container e371e147a6bd
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:27 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy-letsencrypt_1  | Error: can't write to the '/etc/nginx/certs' directory !
nginx-proxy-letsencrypt_1  | Check that '/etc/nginx/certs' directory is export as a writable volume.
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:27 Received event die for container e371e147a6bd
with-nginx-proxy-and-letsencrypt_nginx-proxy-letsencrypt_1 exited with code 1
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:28 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:29 Received event start for container e371e147a6bd
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:29 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy-letsencrypt_1  | Error: can't write to the '/etc/nginx/certs' directory !
nginx-proxy-letsencrypt_1  | Check that '/etc/nginx/certs' directory is export as a writable volume.
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:30 Received event die for container e371e147a6bd
with-nginx-proxy-and-letsencrypt_nginx-proxy-letsencrypt_1 exited with code 1
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:31 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:33 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:34 Received event start for container e371e147a6bd
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:34 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy-letsencrypt_1  | Error: can't write to the '/etc/nginx/certs' directory !
nginx-proxy-letsencrypt_1  | Check that '/etc/nginx/certs' directory is export as a writable volume.
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:35 Received event die for container e371e147a6bd
with-nginx-proxy-and-letsencrypt_nginx-proxy-letsencrypt_1 exited with code 1
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:37 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy_1              | dockergen.1 | 2021/04/07 11:25:38 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by flobeier** [comment]
@jhaals my bad, the read-only flag shouldn't have been there.

**Comment by jhaals** [comment]
Thanks for sorting that problem out.

I have my email address exported as `LETSENCRYPT_EMAIL` but it appears it still tries to use `mail@yourdomain.tld`

```
docker-compose up
Creating with-nginx-proxy-and-letsencrypt_nginx-proxy-letsencrypt_1 ... done
Creating with-nginx-proxy-and-letsencrypt_nginx-proxy_1             ... done
Creating with-nginx-proxy-and-letsencrypt_yopass_1                  ... done
Creating with-nginx-proxy-and-letsencrypt_memcached_1               ... done
Attaching to with-nginx-proxy-and-letsencrypt_nginx-proxy-letsencrypt_1, with-nginx-proxy-and-letsencrypt_memcached_1, with-nginx-proxy-and-letsencrypt_yopass_1, with-nginx-proxy-and-letsencrypt_nginx-proxy_1
nginx-proxy-letsencrypt_1  | Info: running letsencrypt-nginx-proxy-companion version v2.0.0-65-g53d2ac1
nginx-proxy-letsencrypt_1  | Error: can't get nginx-proxy container ID !
nginx-proxy-letsencrypt_1  | Check that you are doing one of the following :
nginx-proxy-letsencrypt_1  | 	- Use the --volumes-from option to mount volumes from the nginx-proxy container.
nginx-proxy-letsencrypt_1  | 	- Set the NGINX_PROXY_CONTAINER env var on the letsencrypt-companion container to the name of the nginx-proxy container.
nginx-proxy-letsencrypt_1  | 	- Label the nginx-proxy container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'.
yopass_1                   | 2021/04/07 12:26:17 Starting yopass server on :80, configured Memcached address: memcached:11211
nginx-proxy_1              | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
nginx-proxy_1              | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
nginx-proxy_1              | forego     | starting dockergen.1 on port 5000
nginx-proxy_1              | forego     | starting nginx.1 on port 5100
nginx-proxy-letsencrypt_1  | Info: Creating Diffie-Hellman group in the background.
nginx-proxy-letsencrypt_1  | A pre-generated Diffie-Hellman group will be used for now while the new one is being created.
nginx-proxy-letsencrypt_1  | Generating DH parameters, 2048 bit long safe prime, generator 2
nginx-proxy_1              | dockergen.1 | 2021/04/07 12:26:19 Generated '/etc/nginx/conf.d/default.conf' from 4 containers
nginx-proxy_1              | dockergen.1 | 2021/04/07 12:26:19 Watching docker events
nginx-proxy-letsencrypt_1  | Reloading nginx proxy (c7fb2c63c5edb7cf12dacf211f1669c2399d5ae84494656893057ebf96740ba4)...
nginx-proxy_1              | dockergen.1 | 2021/04/07 12:26:21 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy-letsencrypt_1  | 2021/04/07 12:26:21 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-proxy-letsencrypt_1  | 2021/04/07 12:26:21 [notice] 68#68: signal process started
nginx-proxy-letsencrypt_1  | Warning: /app/letsencrypt_service_data not found, skipping data from containers.
nginx-proxy-letsencrypt_1  | Sleep for 3600s
nginx-proxy-letsencrypt_1  | 2021/04/07 12:26:23 Generated '/app/letsencrypt_service_data' from 4 containers
nginx-proxy-letsencrypt_1  | 2021/04/07 12:26:23 Running '/app/signal_le_service'
nginx-proxy-letsencrypt_1  | 2021/04/07 12:26:23 Watching docker events
nginx-proxy-letsencrypt_1  | 2021/04/07 12:26:24 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx-proxy-letsencrypt_1  | [Wed Apr  7 12:26:25 UTC 2021] Registering account: https://acme-v02.api.letsencrypt.org/directory
nginx-proxy-letsencrypt_1  | [Wed Apr  7 12:26:27 UTC 2021] Register account Error: {
nginx-proxy-letsencrypt_1  |   "type": "urn:ietf:params:acme:error:invalidEmail",
nginx-proxy-letsencrypt_1  |   "detail": "Error creating new account :: contact email \"mail@yourdomain.tld\" has invalid domain : Domain name does not end with a valid public suffix (TLD)",
nginx-proxy-letsencrypt_1  |   "status": 400
nginx-proxy-letsencrypt_1  | }
nginx-proxy-letsencrypt_1  | grep: /etc/acme.sh/mail@yourdomain.tld/ca/acme-v02.api.letsencrypt.org/account.json: No such file or directory
nginx-proxy-letsencrypt_1  | [Wed Apr  7 12:26:27 UTC 2021] The account url is empty, please run '--update-account' first to update the account info first,
nginx-proxy-letsencrypt_1  | [Wed Apr  7 12:26:27 UTC 2021] Then try again.
nginx-proxy-letsencrypt_1  | Error: no ACME account was found or registered for mail@yourdomain.tld and https://acme-v02.api.letsencrypt.org/directory, certificate creation aborted.
nginx-proxy-letsencrypt_1  | Sleep for 3600s
```

**Comment by flobeier** [comment]
@jhaals if you replace `mail@yourdomain.tld` in `docker-compose.yml` with your e-mail address it should work. Also please change the values for `VIRTUAL_HOST` and `LETSENCRYPT_HOST` to a domain name pointing to your host, otherwise Let's Encrypt won't be able to generate a certificate.

**Comment by jhaals** [comment]
ah yes I should read the readme and not assume that my environment variables get substituted during `docker-compose up` :)

**Pull request merged**
