### PR TITLE
Rename binary to yopass-server and introduce pkg/server

### PR DESCRIPTION
**Pull request by grobie**
In preparation of introducing a yopass CLI command this change frees up
the cmd name "yopass" by renaming the server to "yopass-server". Moving
the types and functions only relevant to the server to a new Go package
will allow to build a smaller Go CLI binary without having to include
all server dependencies.

---

- [x] Tests pass
- [x] yopass-server can be built
- [x] aws-lambda can be built
- [x] Dockerfile can be built
- [x] README updated

I hope I haven't forgotten anything @jhaals.

### CODE REVIEW

**Comment by grobie** [comment]
Hmm, I assume the codeclimate error was silenced before? I guess we could extract the validations into a separate function and save one return statement that way otherwise? Not sure whether the memcached connection error is related to my change or a blip in Github actions?

**Comment by grobie** [comment]
How do you feel about raising codeclimate's return statement threshold? I find it's quite common in Go to end up with more than 4 return statements especially when doing json marshalling/unmarshalling. Extracting such functionality into smaller functions out is not really idiomatic Go code either. I'm about to run into the same problem in the HTTP client.

https://docs.codeclimate.com/docs/advanced-configuration#default-checks

**Comment by jhaals** [comment]
@grobie I agree that bumping the return limit is a good idea 👍

**Comment by jhaals** [comment]
I re-triggered the tests, it was definitely something flaky with github actions when tests ran previously. Don't worry about the Codecov complaining about a .17% drop in tests 😅

**Pull request merged**
