### PR TITLE
fix, add maxLength parameter to lambda deploy

### LINKED ISSUE #263: Broken lambda deploy
When maxLength parameter was added, the lambda deploy was not updated.

### PR DESCRIPTION
**Pull request by tolidano**
Read from environment vars, default to 1024 if unset.
Update serverless.yml to include env var set to 1024.

Fixes #263

### CODE REVIEW

**Comment by tolidano** [comment]
Unclear what the failure is with codecov. Let me know what actions to take on my end.

**Comment by jhaals** [comment]
Thanks a lot for addressing this @tolidano!
Don't worry about the codecov, I've been in the middle of moving away from travis to github actions and most likely messed up the configuration.
This looks all good to me but please make the default 10000 so that it's the same as on the non-lambda version. 1024 will for most be too low as a default.

**Comment by tolidano** [comment]
I think you may wish to consider how this impacts your dynamo capacity unit settings. A 10k secret would take 10 write capacity units, right? 1k each? That was my thinking for selecting 1k. It may make sense to up the WCU (and RCU) from 5 to support 10k secrets. What do you think?

**Comment by jhaals** [comment]
That's a good point, making it 10k should still be within the free capacity limits. It make sense to also raise the throughput to 10.

**Comment by tolidano** [comment]
Adjusted per our conversation.

**Pull request merged**
